name: kurumo
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  firebase_storage: ^11.2.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  cloud_firestore:
  go_router: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  assets:
    - assets/images/
  uses-material-design: true

